spring.application.name=Navy_Project
server.port=8081

# Change only these 3 values if your MySQL is different.
spring.datasource.url=jdbc:mysql://localhost:3306/port_simulation?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dilli@7869$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
